# Generated by Django 5.1.7 on 2025-06-03 18:22

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='image',
            new_name='image_card',
        ),
        migrations.AddField(
            model_name='anime',
            name='image_detail',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.anime_image_upload_path),
        ),
    ]
