# Generated by Django 5.1.7 on 2025-06-08 06:47

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='users/default.png', upload_to=main.models.user_icon),
        ),
    ]
